
DROP  USER PIZZABESTELLUNG_READER;
DROP  USER PIZZABESTELLUNG_WRITER;
DROP  USER PIZZABESTELLUNG_ADMIN;

-- before dropping the roles we MUST drop privileges on owned tables :
DROP OWNED BY  PIZZABESTELLUNG_READER_ROLE      CASCADE;
DROP OWNED BY  PIZZABESTELLUNG_WRITER_ROLE      CASCADE;
DROP OWNED BY  PIZZABESTELLUNG_ADMIN_ROLE       CASCADE;

DROP  ROLE PIZZABESTELLUNG_READER_ROLE;
DROP  ROLE PIZZABESTELLUNG_WRITER_ROLE;
DROP  ROLE PIZZABESTELLUNG_ADMIN_ROLE;