
-- Reader   -----------------------------------------------------------

CREATE ROLE PIZZABESTELLUNG_READER_ROLE;

GRANT  SELECT ON ALL TABLES    IN SCHEMA public TO  PIZZABESTELLUNG_READER_ROLE;

-- WRITER   -------------------------------------------------------

CREATE ROLE PIZZABESTELLUNG_WRITER_ROLE;

GRANT  PIZZABESTELLUNG_READER_ROLE TO PIZZABESTELLUNG_WRITER_ROLE;

GRANT  INSERT, UPDATE ON ALL TABLES    IN SCHEMA public TO   PIZZABESTELLUNG_WRITER_ROLE;
GRANT  SELECT, UPDATE ON ALL SEQUENCES IN SCHEMA public TO   PIZZABESTELLUNG_WRITER_ROLE;

-- Admin    -----------------------------------------------------------

CREATE ROLE PIZZABESTELLUNG_ADMIN_ROLE;

GRANT  PIZZABESTELLUNG_WRITER_ROLE TO PIZZABESTELLUNG_ADMIN_ROLE;

GRANT  CREATE ON SCHEMA public TO PIZZABESTELLUNG_ADMIN_ROLE;

GRANT  DELETE         ON ALL TABLES    IN SCHEMA public TO   PIZZABESTELLUNG_ADMIN_ROLE;
